AddCSLuaFile()
player_manager.AddValidModel("JackaFireSuit","models/DPFilms/jetropolice/Playermodels/pm_policetrench.mdl")
player_manager.AddValidHands("JackaFireSuit","models/DPFilms/jeapons/v_arms_metropolice.mdl",0,"00000000")
player_manager.AddValidModel("JackaHazmatSuit","models/DPFilms/jetropolice/Playermodels/pm_police_bt.mdl")
player_manager.AddValidHands("JackaHazmatSuit","models/DPFilms/jeapons/v_arms_metropolice.mdl",0,"00000000")
player_manager.AddValidModel("JackyEODSuit","models/juggerjaut_player.mdl")
player_manager.AddValidHands("JackyEODSuit","models/DPFilms/jeapons/v_arms_metropolice.mdl",0,"00000000")
game.AddParticles("particles/muzzleflashes_test.pcf")
game.AddParticles("particles/muzzleflashes_test_b.pcf")
game.AddParticles( "particles/gb5_emp.pcf") 
game.AddParticles( "particles/gb5_littleboy.pcf") 
game.AddParticles( "particles/gb5_fatman.pcf") 
game.AddParticles( "particles/gb5_trinity_explo.pcf") 
game.AddParticles( "particles/gb5_blackhole.pcf") 
game.AddParticles( "particles/gb5_redmatter.pcf") 
game.AddParticles( "particles/gb5_idle_special.pcf")  
game.AddParticles( "particles/gb5_large_explosion.pcf")  
game.AddParticles( "particles/gb5_high_explosive.pcf")  
game.AddParticles( "particles/gb5_poison_gas.pcf")  
game.AddParticles( "particles/gb5_wildfire_vial.pcf")  
game.AddParticles( "particles/gb5_fireball.pcf")  
game.AddParticles( "particles/gb5_fireball_wildfire.pcf")  
game.AddParticles( "particles/gb5_fireboom.pcf")  
game.AddParticles( "particles/gb5_grable.pcf")  
game.AddParticles( "particles/gb5_nitro.pcf")  
game.AddParticles( "particles/gb5_napalm.pcf")  
game.AddParticles( "particles/gb5_500lb.pcf")  
game.AddParticles( "particles/gb5_1000lb.pcf")  
game.AddParticles( "particles/gb5_mini_can.pcf")  
game.AddParticles( "particles/gb5_c4.pcf")  
game.AddParticles( "particles/gb5_highyield_nuke.pcf")  
game.AddParticles( "particles/gb5_antimatter_idle.pcf")  
game.AddParticles( "particles/gb5_antimatter_natsu.pcf") 
game.AddParticles( "particles/gb5_exoendo.pcf") 
game.AddParticles( "particles/gb5_fissionbomb.pcf") 
game.AddParticles( "particles/gb5_vx_gas.pcf") 
game.AddParticles( "particles/gb5_tsar_bomba.pcf") 
game.AddParticles( "particles/gb5_fusionbomb.pcf") 
game.AddParticles( "particles/gb5_super_hyper.pcf") 
game.AddParticles( "particles/gb5_rep_attr.pcf") 
game.AddParticles( "particles/gb5_singularity_bomb.pcf") 
game.AddParticles( "particles/gb5_steam_explosion.pcf") 
game.AddParticles( "particles/gb5_light_bomb.pcf") 
game.AddParticles( "particles/gb5_tvirus.pcf") 
game.AddParticles( "particles/gb5_propellant_petrolium.pcf") 
game.AddParticles( "particles/gb5_propellant_oxykerosine.pcf") 
game.AddParticles( "particles/gb5_propellant_hydrogen.pcf") 
game.AddParticles( "particles/gb5_propellant_antimatter.pcf") 
game.AddParticles( "particles/gb5_propellant_trilithium.pcf") 
game.AddParticles( "particles/gb5_davycrockett.pcf")
game.AddParticles( "particles/gb5_liqtiberium.pcf")
game.AddParticles( "particles/gb5_high_explosive_2.pcf")  
game.AddParticles( "particles/gb5_jdam.pcf")  
game.AddParticles( "particles/gb5_icbm_trail.pcf")  
game.AddParticles( "particles/gb5_icbm_small.pcf")  
game.AddParticles( "particles/gb5_tomahawk_trail.pcf")  
game.AddParticles( "particles/gb5_chlorine_gas.pcf")  
game.AddParticles( "particles/gb5_photon_torpedo.pcf")
game.AddParticles( "particles/gb5_50lb.pcf")
game.AddParticles( "particles/gb5_100lb.pcf")