local iconColor = Color( 255, 255, 255, 255 )
killicon.Add( "ent_jack_turret_amateriel", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_grenade", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_mg", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_dmr", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_pistol", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_plinker", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_rifle", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_shotty", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_sniper", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_turret_smg", "vgui/hud/jid_turret_killicon", iconColor )
killicon.Add( "ent_jack_40mmgrenade", "vgui/hud/jid_turret_killicon", iconColor )

killicon.Add( "ent_jack_claymore", "vgui/hud/jid_claymore_killicon", iconColor )
killicon.Add( "ent_jack_seamine", "vgui/hud/jid_seamine_killicon", iconColor )
killicon.Add( "ent_jack_landmine", "vgui/hud/jid_landmine_killicon", iconColor )
killicon.Add( "ent_jack_boundingmine", "vgui/hud/jid_boundingmine_killicon", iconColor )
killicon.Add( "ent_jack_teslasentry", "vgui/hud/jid_teslasentry_killicon", iconColor )
